### ISSUE TITLE
bug: Unable to (de)normalize an array of values

### ISSUE THREAD

**Issue by edcarroll** [mchlbrnd/normalizr-decorators#1]
Hi there,

Love the project, always a fan of using decorators to avoid extra schema definitions everywhere!

Ran into an issue though, I can't work out how to (de)normalize to and from an array of values. In normalizr you just wrap the schema in `[]`, however I've dug through your source and cannot find a way to do it.

Are you able to please advise? Thanks!

**Comment by edcarroll** [comment]
Ended up making a PR to address the issue raised, let me know your thoughts 😄

**Comment by mchlbrnd** [comment]
Sweet! Thanks @edcarroll! Let me review the PR. I'll add the necessary documentation changes.

What are you ideas regarding implementing the missing schema types? I'll add some issues for these as well.

Cheers,
Michael

PS. sorry for the late reply!

**Comment by edcarroll** [comment]
Hey @mchlbrnd, no worries, thank you for getting back to me 😄 

So I ended up adding a few things forgetting there was a PR on my fork, so let me know if there's anything in there you don't like.

Hadn't yet thought about adding the other types yet, was basically adding functionality as I ran into it. Will be able to come back to this in a few days though (I hope) with some ideas 😄

**Comment by mchlbrnd** [comment]
I just added some more issues. No worries about the additional stuff in the PR. It is very welcome!
